baseURL = "https://www.petersell.com/"
languageCode = "de"
defaultContentLanguage = 'de'
title = "Andreas Petersell"
paginate = 10
copyright = "Sämtliche Beiträge stehen unter einer [Creative Commons Namensnennung 4.0 International Lizenz](https://creativecommons.org/licenses/by/4.0/)."

[author]
  name = "Andreas Petersell"

[params]
   author = "Andreas Petersell"
   mainSections = ["blog", "status"]
   description = "Privater Blog eines DITA-Writers."

[menu]

  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    identifier = "statusarchiv"
    name = "Microblog"
    url = "/archive/status/"
    weight = 20  

  [[menu.main]]
    identifier = "categories"
    name = "Kategorien"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "Stichwörter"
    url = "/tags/"
    weight = 40 

  [[menu.main]]
    identifier = "impressum"
    name       = "Impressum"
    url        = "/homepage/impressum/"
    weight     = 70  

[taxonomies]
category = "categories"
tag = "tags"
signatur = "signaturen"

[mediaTypes]
    [mediaTypes."application/atom+xml"]
        suffixes = ["atom", "atom.xml"] # You can remove the "atom.xml" if you want
    
    # Redefining RSS media type for the additional suffix
    [mediaTypes."application/rss+xml"]
        suffixes = ["rss", "rss.xml"] # You can remove the "rss.xml" if you want

[markup.goldmark.renderer]
unsafe = true


# Including all of the feed output formats in the build
[outputFormats]
    [outputFormats.Rss]
        mediaType = "application/rss+xml"
        baseName = "index"

    [outputFormats.Atom]
        mediaType = "application/atom+xml"
        baseName = "index"

# Indicating what output formats shall be included 
# for the following kinds
[outputs]
    # .Site.BaseURL/index.* is available 
    home = ["HTML", "JSON", "RSS", "ATOM"]

    # .Site.BaseURL/$section/index.* is available
    section = ["HTML", "JSON", "RSS", "ATOM"] 

# https://gohugo.io/about/security/
[security]
  [security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osenv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|GO\w+|(XDG_CONFIG_)?HOME|USERPROFILE|SSH_AUTH_SOCK|DISPLAY|LANG)$']
