[build]
 publish = "public"
 command = "bundle && hugo --minify"

[context.production.environment]
 HUGO_VERSION = "0.126.0"
 HUGO_ENV = "production"
 HUGO_ENABLEGITINFO = "true"

[context.split1]
 command = "bundle && hugo --minify --enableGitInfo"

[context.split1.environment]
 HUGO_VERSION = "0.126.0"
 HUGO_ENV = "production"

[context.deploy-preview]
 command = "bundle && hugo --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
 HUGO_VERSION = "0.126.0"

[context.branch-deploy]
 command = "bundle && hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
 HUGO_VERSION = "0.126.0"

[context.next.environment]
 HUGO_ENABLEGITINFO = "true"